apiVersion: v1
kind: Service
metadata:
  name: test
  annotations:
    # Name of the load balancer (customizable by the user)
    service.beta.kubernetes.io/utho-loadbalancer-name: "k8s-lb-custom-name"

    # Algorithm for load balancing; options: "roundrobin" or "leastconn"
    service.beta.kubernetes.io/utho-loadbalancer-algorithm: "roundrobin"

    # Enable sticky sessions; options: "true" or "false"
    # uncomment to use
    # service.beta.kubernetes.io/utho-loadbalancer-sticky-session-enabled: "falae"

    # Redirect HTTP traffic to HTTPS; options: "true" or "false"
    # This option only work for port 80 and 443
    # uncomment to use
    # service.beta.kubernetes.io/utho-loadbalancer--redirect-http-to-https: "falae"

    # SSL certificate ID (required for enabling HTTPS)
    # This option only work for port 80 and 443
    # service.beta.kubernetes.io/utho-loadbalancer-ssl-id: "ssl-cert-id-12345"
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
