apiVersion: v1
kind: Service
metadata:
  name: test-lb-private
  annotations:
    # Network type set to private
    service.beta.kubernetes.io/utho-loadbalancer-network-type: "private"
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
