package v1alpha1

type StatusPhase string

const (
	RunningPhase                StatusPhase = "RUNNING"
	LBPendingPhase              StatusPhase = "LB_PENDING"
	LBCreatedPhase              StatusPhase = "LB_CREATED"
	LBErrorPhase                StatusPhase = "LB_ERROR"
	LBDeletionPendingPhase      StatusPhase = "LB_DELETION_PENDING"
	LBDeletedPhase              StatusPhase = "LB_DELETED"
	LBDeletionErrorPhase        StatusPhase = "LB_DELETION_ERROR"
	TGPendingPhase              StatusPhase = "TG_PENDING"
	TGCreatedPhase              StatusPhase = "TG_CREATED"
	TGErrorPhase                StatusPhase = "TG_ERROR"
	TGDeletionPendingPhase      StatusPhase = "TG_DELETION_PENDING"
	TGDeletedPhase              StatusPhase = "TG_DELETED"
	TGDeletionErrorPhase        StatusPhase = "TG_DELETION_ERROR"
	LBAttachmentPendingPhase    StatusPhase = "LB_ATTACHMENT_PENDING"
	LBAttachmentCreatedPhase    StatusPhase = "LB__ATTACHMENT_CREATED"
	LBAttachmentErrorPhase      StatusPhase = "LB_ATTACHMENT_ERROR"
	FrontendPendingPhase        StatusPhase = "FRONTEND_PENDING"
	FrontendCreatedPhase        StatusPhase = "FRONTEND_CREATED"
	FrontendErrorPhase          StatusPhase = "FRONTEND_ERROR"
	TGAttachmentPendingPhase    StatusPhase = "TG_ATTACHMENT_PENDING"
	TGAttachmentCreatedPhase    StatusPhase = "TG_ATTACHMENT_CREATED"
	TGAttachmentErrorPhase      StatusPhase = "TG_ATTACHMENT_PHASE"
	ACLPendingPhase             StatusPhase = "ACL_PENDING"
	ACLCreatedPhase             StatusPhase = "ACL_CREATED"
	ACLErrorPhase               StatusPhase = "ACL_ERROR"
	AdvancedRoutingPendingPhase StatusPhase = "ADVANCED_ROUTING_PENDING"
	AdvancedRoutingCreatedPhase StatusPhase = "ADVANCED_ROUTING_CREATED"
	AdvancedRoutingErrorPhase   StatusPhase = "ADVANCED_ROUTING_ERROR"
	DomainPendingPhase          StatusPhase = "DOMAIN_PENDING"
	DomainCreatedPhase          StatusPhase = "DOMAIN_CREATED"
	DomainErrorPhase            StatusPhase = "DOMAIN_ERROR"
	DomainRecordsPendingPhase   StatusPhase = "DOMAIN_RECORDS_PENDING"
	DomainRecordsCreatedPhase   StatusPhase = "DOMAIN_RECORDS_CREATED"
	DomainRecordsErrorPhase     StatusPhase = "DOMAIN_RECORDS_ERROR"
)
